# Generated by Django 5.0.1 on 2024-01-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_category_alter_comment_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
