# Generated by Django 5.0.1 on 2024-01-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='article.article'),
        ),
    ]
