# Generated by Django 5.0.1 on 2024-01-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_content_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='article.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='top_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
